using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NuggetMod.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class NuggetModSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        context.RegisterSourceOutput(classDeclarations, static (ctx, classes) =>
        {
            // Find class that implements IPlugin
            var pluginClass = classes.FirstOrDefault(c =>
            {
                if (c.Identifier.Text == "NativeEntry")
                    return false;

                var baseList = c.BaseList;
                if (baseList == null)
                    return false;

                return baseList.Types.Any(t =>
                {
                    var typeName = t.Type.ToString();
                    return typeName == "IPlugin" || typeName.Contains("IPlugin");
                });
            });

            if (pluginClass == null)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "NUGMOD001",
                        title: "No IPlugin implementation found",
                        messageFormat: "No class implementing IPlugin was found. Please create a class that implements NuggetMod.Interface.IPlugin.",
                        category: "NuggetMod",
                        defaultSeverity: DiagnosticSeverity.Warning,
                        isEnabledByDefault: true),
                    Location.None));
                return;
            }

            var namespaceName = GetNamespace(pluginClass);
            var className = pluginClass.Identifier.Text;
            var fullClassName = string.IsNullOrEmpty(namespaceName)
                ? className
                : $"{namespaceName}.{className}";

            var source = GenerateNativeEntrySource(namespaceName, fullClassName);
            ctx.AddSource("NuggetMod.NativeEntry.g.cs", source);
        });
    }

    private static string GetNamespace(ClassDeclarationSyntax classDecl)
    {
        var parent = classDecl.Parent;
        while (parent != null)
        {
            if (parent is NamespaceDeclarationSyntax nsDecl)
                return nsDecl.Name.ToString();
            if (parent is FileScopedNamespaceDeclarationSyntax fsNsDecl)
                return fsNsDecl.Name.ToString();
            parent = parent.Parent;
        }
        return "";
    }

    private static string GenerateNativeEntrySource(string namespaceName, string pluginFullClassName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by NuggetMod Source Generator");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using NuggetMod.Enum.Metamod;");
        sb.AppendLine("using NuggetMod.Interface;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine("public class NativeEntry : PluginEntry");
        sb.AppendLine("{");
        sb.AppendLine("    static NativeEntry()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Interface = new {pluginFullClassName}();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"GiveFnptrsToDll\")]");
        sb.AppendLine("    public static void UnmanagedGiveFnptrsToDll(nint pengfuncsFromEngine, nint pGlobals)");
        sb.AppendLine("        => Native_GiveFnptrsToDll(pengfuncsFromEngine, pGlobals);");
        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"Meta_Init\", CallConvs = [typeof(CallConvCdecl)])]");
        sb.AppendLine("    public static void UnmanagedMeta_Init()");
        sb.AppendLine("        => Native_Meta_Init();");
        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"Meta_Query\", CallConvs = [typeof(CallConvCdecl)])]");
        sb.AppendLine("    public static int UnmanagedMeta_Query(nint interfaceVersion, nint plinfo, nint pMetaUtilFuncs)");
        sb.AppendLine("        => Native_Meta_Query(interfaceVersion, plinfo, pMetaUtilFuncs);");
        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"Meta_Attach\", CallConvs = [typeof(CallConvCdecl)])]");
        sb.AppendLine("    public static int UnmanagedMeta_Attach(PluginLoadTime now, nint pFunctionTable, nint pMGlobals, nint pGamedllFuncs)");
        sb.AppendLine("        => Native_Meta_Attach(now, pFunctionTable, pMGlobals, pGamedllFuncs);");
        sb.AppendLine();
        sb.AppendLine("    [UnmanagedCallersOnly(EntryPoint = \"Meta_Detach\", CallConvs = [typeof(CallConvCdecl)])]");
        sb.AppendLine("    public static int UnmanagedMeta_Detach(PluginLoadTime now, PluginUnloadReason reason)");
        sb.AppendLine("        => Native_Meta_Detach(now, reason);");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
